const String HOME_TITLE = "My Future Car";
const String CARS_TITLE = "Cars";
const int CAR_TAB = 0;
const int CAR_TYPE_TAB = 1;
const int BRAND_TAB = 2;
const int COLOR_TAB = 3;
const int POWER_CLASS_TAB = 4;
const int MY_GEARBOX_TAB = 5;
const String BASE_URL = "192.168.100.27:5000";